fgms_survey_homepage:
    path:     /
    defaults: { _controller: FgmsSurveyBundle:Default:index }

# start routes    
fgms_survey_start:
    path:     /{slug}/start/
    defaults: { _controller: FgmsSurveyBundle:Default:start, group: false }
    
fgms_survey_start_with_group:
    path:     /{group}/{slug}/start/
    defaults: { _controller: FgmsSurveyBundle:Default:start }    

# survey routes    
fgms_survey_property:
    path:     /{slug}/survey/
    defaults: { _controller: FgmsSurveyBundle:Default:survey, group: false }
    
fgms_survey_property_with_group:
    path:     /{group}/{slug}/survey/
    defaults: { _controller: FgmsSurveyBundle:Default:survey }
    
# finish routes    
fgms_survey_finish:
    path:     /{slug}/finish/
    defaults: { _controller: FgmsSurveyBundle:Default:finish, group: false }    
    
fgms_survey_finish_with_group:
    path:     /{group}/{slug}/finish/
    defaults: { _controller: FgmsSurveyBundle:Default:finish }
    
# Result routes   
fgms_survey_results:
    path: /{slug}/results/
    defaults : { _controller: FgmsSurveyBundle:Default:results, group: false}
    
fgms_survey_results_with_group:
    path: /{group}/{slug}/results/
    defaults : { _controller: FgmsSurveyBundle:Default:results}
    
# email preview routes
fgms_survey_emailpreview:
    path: /{slug}/email/
    defaults : { _controller: FgmsSurveyBundle:Default:emailpreview, group: false}
    
fgms_survey_emailpreview_with_group:
    path: /{group}/{slug}/email/
    defaults : { _controller: FgmsSurveyBundle:Default:emailpreview}
    
# csv routes
fgms_survey_csv:
    path: /{slug}/csv/
    defaults : { _controller: FgmsSurveyBundle:Default:downloadcsv, group: false }

fgms_survey_csv_with_group:
    path: /{group}/{slug}/csv/
    defaults : { _controller: FgmsSurveyBundle:Default:downloadcsv }

#cron routes
fgms_survey_cron:
    path: /cron/
    defaults: {_controller: FgmsSurveyBundle:Default:crontrigger }

fgms_survey_cron_property:
    path: /cron/{slug}/
    defaults: {_controller: FgmsSurveyBundle:Default:cron, group: false }
    
fgms_survey_cron_property_with_group:
    path: /cron/{group}/{slug}/
    defaults: {_controller: FgmsSurveyBundle:Default:cron, group: false }

# Charting routes
fgms_survey_chart:
    path: /{slug}/chart/{question}/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:chart, group: false }
    requirements: {question: '\d+', days: '\d+|yeartodate' }
fgms_survey_chart_with_group:
    path: /{group}/{slug}/chart/{question}/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:chart }
    requirements: {question: '\d+', days: '\d+|yeartodate' }
fgms_survey_chart_csv:
    path: /{slug}/chartcsv/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:chartCsv, group: false }
    requirements: {question: '\d+', days: '\d+|yeartodate' }
fgms_survey_chart_csv_with_group:
    path: /{group}/{slug}/chartcsv/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:chartCsv }
    requirements: {question: '\d+', days: '\d+|yeartodate' }
fgms_survey_chart_range:
    path: /{slug}/chart/{question}/{fromday}/{frommonth}/{fromyear}/{today}/{tomonth}/{toyear}/
    defaults: {_controller: FgmsSurveyBundle:Default:chartRange, group: false }
    requirements: {question: '\d+', fromday: '\d{2}', frommonth: '\d{2}', fromyear: '\d{4}', today: '\d{2}', tomonth: '\d{2}', toyear: '\d{4}' }
fgms_survey_chart_range_with_group:
    path: /{group}/{slug}/chart/{question}/{fromday}/{frommonth}/{fromyear}/{today}/{tomonth}/{toyear}/
    defaults: {_controller: FgmsSurveyBundle:Default:chartRange }
    requirements: {question: '\d+', fromday: '\d{2}', frommonth: '\d{2}', fromyear: '\d{4}', today: '\d{2}', tomonth: '\d{2}', toyear: '\d{4}' }

# Guest feedback routes
fgms_survey_feedback:
    path: /{slug}/feedback/{question}/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:feedback, group: false }
    requirements: {question: '\d+', days: '\d+|yeartodate' }
fgms_survey_feedback_with_group:
    path: /{group}/{slug}/feedback/{question}/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:feedback }
    requirements: {question: '\d+', days: '\d+|yeartodate' }
fgms_survey_feedback_csv:
    path: /{slug}/feedbackcsv/{question}/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:feedbackCsv, group: false }
    requirements: {question: '\d+', days: '\d+|yeartodate' }
fgms_survey_feedback_csv_with_group:
    path: /{group}/{slug}/feedbackcsv/{question}/{days}/
    defaults: {_controller: FgmsSurveyBundle:Default:feedbackCsv }
    requirements: {question: '\d+', days: '\d+|yeartodate' }